# docker-compose.yml (VERSÃO FINAL)
version: "3.8"

networks:
  esus-net:
    driver: bridge

volumes:
  esus-db-data:
    driver: local

services:
  # ---------------------------------------------------------------------------
  # SERVIÇO DO BANCO DE DADOS (esus-db) - COM HEALTHCHECK
  # ---------------------------------------------------------------------------
  esus-db:
    image: postgres:9.6-alpine
    container_name: esus-db
    restart: unless-stopped
    volumes:
      - esus-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-esus}
      - POSTGRES_USER=${POSTGRES_USER:-esus}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Será lido do Secret do Coolify
      - TZ=${TZ:-America/Sao_Paulo}
    networks:
      - esus-net
    # --- NOVO: Verificação de saúde para o banco de dados ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-esus} -d ${POSTGRES_DB:-esus}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ---------------------------------------------------------------------------
  # SERVIÇO DA APLICAÇÃO (esus-app) - MODIFICADO
  # ---------------------------------------------------------------------------
  esus-app:
    build:
      context: ./esus-app-dockerfile
      args:
        URL_DOWNLOAD_ESUS: ${URL_DOWNLOAD_ESUS}
    container_name: esus-app
    restart: unless-stopped
    # --- MODIFICADO: Agora espera o 'healthcheck' do banco passar ---
    depends_on:
      esus-db:
        condition: service_healthy
    environment:
      - APP_DB_URL=jdbc:postgresql://esus-db:5432/${POSTGRES_DB:-esus}
      - APP_DB_USER=${POSTGRES_USER:-esus}
      - APP_DB_PASSWORD=${POSTGRES_PASSWORD} # Será lido do Secret do Coolify
      - TZ=${TZ:-America/Sao_Paulo}
    networks:
      - esus-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esus-app.rule=Host(`${FQDN_ESUS}`)"
      - "traefik.http.routers.esus-app.entrypoints=https"
      - "traefik.http.routers.esus-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.esus-app.loadbalancer.server.port=8080"
